version: '3.8'

services:
  rosserial:
    build:
      context: .
      dockerfile: rosserial.dockerfile

    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/cesarruiz/Projects/sensor_actuator_pkg:/root/Arduino/libraries/Hydrus
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

    environment:
      - ARDUINO_BOARD=arduino:avr:uno